export const DELETE_ITEM = "DELETE_ITEM"
export const GET_ITEMS = "GET_ITEMS"
export const GET_ITEM = "GET_ITEM"
export const SET_ERROR = "SET_ERROR"
export const SET_EDIT_ITEMS = "SET_EDIT_ITEMS"
export const SET_TITLE = "SET_TITLE"
export const SET_COMPLETE = "SET_COMPLETE"
export const SET_PAG = "SET_PAG"
export const SET_LIMIT = "SET_LIMIT"

